version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.21
    #working_directory: /go/src/github.com/muraenateam/muraena

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps:
      - checkout
      - run:
          name: "Should we release?"
          command: |
            if [[ ! "$(git show -s --format=%s)" == "Releasing"* ]]; then circleci-agent step halt; fi


      - run: make pre # pull and build dependencies for the project
      - run: go install github.com/mitchellh/gox@latest
      - run: go install github.com/tcnksm/ghr@latest

      - run: gox -os="linux darwin windows" -arch="amd64" -ldflags "-X main.Version=$BUILD_VERSION -X main.BuildDate=$BUILD_DATE" -output "dist/muraena_{{.OS}}_{{.Arch}}"
      - run: gox -os="linux darwin" -arch="arm64" -ldflags "-X main.Version=$BUILD_VERSION -X main.BuildDate=$BUILD_DATE" -output "dist/muraena_{{.OS}}_{{.Arch}}"
      - run:
          name: "Create release release"
          command: |
            VERSION=$(cat core/banner.go | grep Version | cut -d '"' -f 2)
            bash ./.circleci/auto-release.sh ./dist/*
            cat RELEASE.md
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "v$VERSION" -body "$(cat RELEASE.md)" -draft -replace -delete "v$VERSION" dist/
  build_docker_image:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout 
      - setup_remote_docker:
          docker_layer_caching:false 
      run:
        name: build Docker image
        command:|
          docker build -t mumu -t rakyat/mumuapp:latest
          echo $dockerpass | docker login -u rakyat135 --password-stdin
          docker push rakyat/mumuapp:latest
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - build_docker_image


